name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install apt-dep
      run: sudo apt-get install -y flex bison byacc make m4
    - uses: actions/checkout@v2
    - name: make
      run: make all
