name: C/C++ CI

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install apt-dep
      run: sudo apt-get install -y flex bison byacc make m4
    - uses: actions/checkout@v2
    - name: make
      run: make all
    - name: Zip Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
        type: zip
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: 'release.zip'
        token: ${{ secrets.RELEASE }}
